package grafica;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.SQL.SQLCabanna;
import logica.SQL.SQLReserva;
import logica.SQL.SQLTurista;

public class Herramientas extends javax.swing.JPanel {

    String view;

    /**
     * Panel con las herramientas que son necesarias en los menues con tablas.
     *
     */
    public Herramientas() {
        this.view = "CABANNAS";

    }

    public Herramientas(String view) {
        this.view = view;
    }

    public void buildHerramientas(DefaultComboBoxModel aModel, DefaultComboBoxModel aModelSort) {
        initComponents();
        this.setSize(454, 145);
        cmbFilter.setModel(aModel);
        cmbSort.setModel(aModelSort);
        
    }
    
    public DefaultComboBoxModel camposComboB(String view, DefaultComboBoxModel Def) {
        //Va a setear el modelo por defecto de los combo boxes
        Def = new DefaultComboBoxModel();
        switch (view) {
            case "TURISTAS":
                Def.addElement("CI");
                Def.addElement("Nombre");
                Def.addElement("Apellido");
                Def.addElement("Fecha Nacimiento");
                Def.addElement("Teléfono");
                Def.addElement("Calle");
                Def.addElement("Número");
                Def.addElement("Localidad");
                break;
            case "CABANNAS":
                Def.addElement("ID");
                Def.addElement("Nº Habitaciones");
                Def.addElement("Nº Camas");
                Def.addElement("Nº Baños");
                Def.addElement("Nº Huéspedes");
                Def.addElement("Descripción");
                Def.addElement("Aire Acon.");
                Def.addElement("Parrillero");
                Def.addElement("Costo Hr.");
                break;
            default:
                Def.addElement("Código");
                Def.addElement("Fecha Inicio");
                Def.addElement("Fecha Fin");
                Def.addElement("Confirmada");
                Def.addElement("Cancelada");
                Def.addElement("CI");
                Def.addElement("ID");
        }
        return Def;
    }

    public DefaultComboBoxModel camposSort(String view, DefaultComboBoxModel Def) { //Va a setear el modelo por defecto del combo box del sort
        Def = new DefaultComboBoxModel();
        switch (view) {
            case "TURISTAS":
                Def.addElement("CI");
                Def.addElement("Nombre");
                Def.addElement("Apellido");
                Def.addElement("Fecha Nacimiento");
                Def.addElement("Teléfono");
                break;
            case "CABANNAS":
                Def.addElement("ID");
                Def.addElement("Nº Habitaciones");
                Def.addElement("Nº Camas");
                Def.addElement("Nº Baños");
                Def.addElement("Nº Huéspedes");
                Def.addElement("Aire Acon.");
                Def.addElement("Parrillero");
                Def.addElement("Costo Hr.");
                break;
            default:
                Def.addElement("Código");
                Def.addElement("Fecha Inicio");
                Def.addElement("Fecha Fin");
                Def.addElement("Confirmada");
                Def.addElement("Cancelada");
                Def.addElement("CI");
                Def.addElement("ID");
                break;
        }
        return Def;
    }
    

    
    public void horizontalView(){
        this.setSize(940, panelBuscar.getHeight());
        panelBuscar.setLocation(0, 0);
        panelOrdenar.setSize(this.getWidth(), panelBuscar.getHeight());
        lblOrdenar.setLocation(10, (panelOrdenar.getHeight()/2)-lblOrdenar.getHeight());
        cmbSort.setLocation(lblOrdenar.getLocation().x + lblOrdenar.getWidth()+10, (panelOrdenar.getHeight()/2)-cmbSort.getHeight());
        btnSort.setLocation(cmbSort.getLocation().x + cmbSort.getWidth()+10, (panelOrdenar.getHeight()/2) - btnSort.getHeight());
        cmbSort.updateUI();
        panelOrdenar.setLocation(panelBuscar.getWidth()+10,0);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        fieldPattern = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        btnCanceladas = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        cmbVisualizadas = new javax.swing.JComboBox<>();
        panelOrdenar = new javax.swing.JPanel();
        btnSort = new javax.swing.JLabel();
        lblOrdenar = new javax.swing.JLabel();
        cmbSort = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        panelBuscar.setBackground(new java.awt.Color(236, 235, 255));
        panelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelBuscar.setPreferredSize(new java.awt.Dimension(100, 83));
        panelBuscar.setLayout(null);

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(43, 41, 41));
        lblBuscar.setText("Buscar");
        lblBuscar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelBuscar.add(lblBuscar);
        lblBuscar.setBounds(10, 10, 50, 20);

        fieldPattern.setPreferredSize(new java.awt.Dimension(144, 21));
        panelBuscar.add(fieldPattern);
        fieldPattern.setBounds(70, 10, 144, 21);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnSearch.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        panelBuscar.add(btnBuscar);
        btnBuscar.setBounds(360, 10, 30, 26);

        cmbFilter.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbFilter.setForeground(new java.awt.Color(43, 41, 41));
        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });
        panelBuscar.add(cmbFilter);
        cmbFilter.setBounds(230, 10, 120, 21);

        btnCanceladas.setText("Canceladas");
        btnCanceladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceladasActionPerformed(evt);
            }
        });
        panelBuscar.add(btnCanceladas);
        btnCanceladas.setBounds(10, 50, 110, 20);

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseClicked(evt);
            }
        });
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        panelBuscar.add(btnVisualizar);
        btnVisualizar.setBounds(300, 50, 80, 23);

        cmbVisualizadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semana", "Mes" }));
        panelBuscar.add(cmbVisualizadas);
        cmbVisualizadas.setBounds(206, 50, 80, 20);

        add(panelBuscar);
        panelBuscar.setBounds(0, 0, 454, 83);

        panelOrdenar.setBackground(new java.awt.Color(236, 235, 255));
        panelOrdenar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelOrdenar.setPreferredSize(new java.awt.Dimension(454, 59));
        panelOrdenar.setLayout(null);

        btnSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnOrdenar.png"))); // NOI18N
        btnSort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOrdenar.add(btnSort);
        btnSort.setBounds(320, 10, 111, 22);

        lblOrdenar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblOrdenar.setForeground(new java.awt.Color(43, 41, 41));
        lblOrdenar.setText("Ordenar Tabla");
        lblOrdenar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblOrdenar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblOrdenar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelOrdenar.add(lblOrdenar);
        lblOrdenar.setBounds(10, 10, 100, 20);

        cmbSort.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbSort.setForeground(new java.awt.Color(43, 41, 41));
        cmbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortActionPerformed(evt);
            }
        });
        panelOrdenar.add(cmbSort);
        cmbSort.setBounds(150, 10, 160, 21);

        add(panelOrdenar);
        panelOrdenar.setBounds(0, 100, 454, 59);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSortActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        String patron = fieldPattern.getText();
        String atributo;

        switch (cmbFilter.getSelectedItem().toString()) {
            case "ID":
                atributo = "id";
                break;
            case "Nº Habitaciones":
                atributo = "cantHabitaciones";
                break;
            case "Nº Camas":
                atributo = "cantCamas";
                break;
            case "Nº Baños":
                atributo = "cantBannos";
                break;
            case "Nº Huéspedes":
                atributo = "cantHuespedes";
                break;
            case "Descripción":
                atributo = "descripcion";
                break;
            case "Aire Acon.":
                atributo = "aireAcondicionado";
                break;
            case "Parrillero":
                atributo = "parrillero";
                break;
            case "Costo Hr.":
                atributo = "costHour";
                break;
            default:
                atributo = "";
                break;
        }

        SQLCabanna sqlCabanna = new SQLCabanna();
        DefaultTableModel busqueda = sqlCabanna.select(patron, atributo);
        Index.paintTabla(busqueda, view);
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnCanceladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceladasActionPerformed
        SQLReserva sqlReserva = new SQLReserva();
        this.view = "RESERVAS_CANCELADAS";
        DefaultTableModel busqueda = sqlReserva.selectCanceladas();
        Index.paintTabla(busqueda, view);
    }//GEN-LAST:event_btnCanceladasActionPerformed

    private void btnVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseClicked
        SQLReserva sqlReserva = new SQLReserva();
        this.view = "RESERVAS_VISTA";
        DefaultTableModel busqueda = sqlReserva.selectVisualizar(cmbVisualizadas.getSelectedItem().toString().toUpperCase());
        Index.paintTabla(busqueda, view);
    }//GEN-LAST:event_btnVisualizarMouseClicked

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnCanceladas;
    private javax.swing.JLabel btnSort;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JComboBox<String> cmbSort;
    public javax.swing.JComboBox<String> cmbVisualizadas;
    private javax.swing.JTextField fieldPattern;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblOrdenar;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelOrdenar;
    // End of variables declaration//GEN-END:variables
}
