package grafica;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.SQL.SQLCabanna;


public class Herramientas extends javax.swing.JPanel {

    /**
     * Panel con las herramientas que son necesarias
     * en los menues con tablas.
     * @param aModel Esto es mágico, contiene el modelo de items que se mostrará en la búsqueda
     * @param aModelSort Idem. pero muestra el del cmbSort
     */
    public Herramientas(DefaultComboBoxModel aModel, DefaultComboBoxModel aModelSort) {
        initComponents();
        this.setSize(454,145);
        cmbFilter.setModel(aModel);
        cmbSort.setModel(aModelSort);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        fieldPattern = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JLabel();
        panelOrdenar = new javax.swing.JPanel();
        btnSort = new javax.swing.JLabel();
        lblOrdenar = new javax.swing.JLabel();
        cmbSort = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBuscar.setBackground(new java.awt.Color(236, 235, 255));
        panelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelBuscar.setPreferredSize(new java.awt.Dimension(100, 83));
        panelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(43, 41, 41));
        lblBuscar.setText("Buscar");
        lblBuscar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 20));

        fieldPattern.setPreferredSize(new java.awt.Dimension(144, 21));
        panelBuscar.add(fieldPattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnBuscar.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        panelBuscar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        cmbFilter.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbFilter.setForeground(new java.awt.Color(43, 41, 41));
        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });
        panelBuscar.add(cmbFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, -1));

        btnEliminar.setLabelFor(this);
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        panelBuscar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 20));

        add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 454, -1));

        panelOrdenar.setBackground(new java.awt.Color(236, 235, 255));
        panelOrdenar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelOrdenar.setPreferredSize(new java.awt.Dimension(454, 59));
        panelOrdenar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnOrdenar.png"))); // NOI18N
        btnSort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOrdenar.add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        lblOrdenar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblOrdenar.setForeground(new java.awt.Color(43, 41, 41));
        lblOrdenar.setText("Ordenar Tabla");
        lblOrdenar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblOrdenar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblOrdenar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelOrdenar.add(lblOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        cmbSort.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbSort.setForeground(new java.awt.Color(43, 41, 41));
        cmbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortActionPerformed(evt);
            }
        });
        panelOrdenar.add(cmbSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 160, -1));

        add(panelOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSortActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        String patron=fieldPattern.getText();
        String atributo;
        switch(cmbFilter.getSelectedItem().toString()){
            case "ID":
                atributo="id";
                break;
            case "Nº Habitaciones":
                atributo="cantHabitaciones"; 
                break;
            case "Nº Camas":
                atributo="cantCamas"; 
                break;
            case "Nº Baños":
                atributo="cantBannos"; 
                break; 
            case "Nº Huéspedes":
                atributo="cantHuespedes"; 
                break;
            case "Descripción":
                atributo="descripcion"; 
                break;
            case "Aire Acon.":
                atributo="aireAcondicionado"; 
                break;
            case "Parrillero":
                atributo="parrillero"; 
                break;
            case "Costo Hr.":
                atributo="costHour"; 
                break; 
            default:
                atributo="";
                break;
        }
        SQLCabanna Auxiliar=new SQLCabanna();
        DefaultTableModel Busqueda=Auxiliar.select(patron, atributo);
        Index.mostrarTabla(Busqueda);
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        String patron=fieldPattern.getText();
        try{
        SQLCabanna Auxiliar=new SQLCabanna();
        boolean resultado=Auxiliar.eliminar(Short.parseShort(patron));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Debe insertar un id");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnSort;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JComboBox<String> cmbSort;
    private javax.swing.JTextField fieldPattern;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblOrdenar;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelOrdenar;
    // End of variables declaration//GEN-END:variables
}
