package grafica;

import javax.swing.DefaultComboBoxModel;


public class Herramientas extends javax.swing.JPanel {

    /**
     * Panel con las herramientas que son necesarias
     * en los menues con tablas.
     * @param aModel Esto es mágico, contiene el modelo de items que se mostrará
     */
    public Herramientas(DefaultComboBoxModel aModel, DefaultComboBoxModel aModelSort) {
        initComponents();
        this.setSize(454,145);
        cmbFilter.setModel(aModel);
        cmbSort.setModel(aModelSort);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        fieldPattern = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        panelOrdenar = new javax.swing.JPanel();
        btnBuscar1 = new javax.swing.JLabel();
        lblOrdenar = new javax.swing.JLabel();
        cmbSort = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBuscar.setBackground(new java.awt.Color(236, 235, 255));
        panelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelBuscar.setPreferredSize(new java.awt.Dimension(100, 83));
        panelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(43, 41, 41));
        lblBuscar.setText("Buscar");
        lblBuscar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 20));

        fieldPattern.setPreferredSize(new java.awt.Dimension(144, 21));
        panelBuscar.add(fieldPattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnBuscar.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBuscar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        cmbFilter.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbFilter.setForeground(new java.awt.Color(43, 41, 41));
        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });
        panelBuscar.add(cmbFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, -1));

        add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 454, -1));

        panelOrdenar.setBackground(new java.awt.Color(236, 235, 255));
        panelOrdenar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelOrdenar.setPreferredSize(new java.awt.Dimension(454, 59));
        panelOrdenar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnOrdenar.png"))); // NOI18N
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOrdenar.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        lblOrdenar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblOrdenar.setForeground(new java.awt.Color(43, 41, 41));
        lblOrdenar.setText("Ordenar Tabla");
        lblOrdenar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblOrdenar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblOrdenar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelOrdenar.add(lblOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        cmbSort.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbSort.setForeground(new java.awt.Color(43, 41, 41));
        cmbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortActionPerformed(evt);
            }
        });
        panelOrdenar.add(cmbSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 160, -1));

        add(panelOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSortActionPerformed

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnBuscar1;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JComboBox<String> cmbSort;
    private javax.swing.JTextField fieldPattern;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblOrdenar;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelOrdenar;
    // End of variables declaration//GEN-END:variables
}
