/*
 * To change this license header, choose License Headers in Project Properties.
 * and open the template in the editor.
 * To change this template file, choose Tools | Templates
 */
package grafica;

import logica.Cabanna;
import logica.SQL.SQLCabanna;

/**
 *
 * @author Matías Garibotti
 */
public class ingCabanna extends javax.swing.JPanel {

    /**
     * Creates new form ingCabanna
     */
    
    private byte cntHabitaciones;
    private byte cntCamas;
    private byte cntBannos;
    private String descripcion;
    private boolean aireAcondicionado;
    private boolean parrillero;
    private short costoHour;

    public byte getCntHabitaciones() {
        return cntHabitaciones;
    }

    public void setCntHabitaciones(byte cntHabitaciones) {
        this.cntHabitaciones = cntHabitaciones;
    }

    public byte getCntCamas() {
        return cntCamas;
    }

    public void setCntCamas(byte cntCamas) {
        this.cntCamas = cntCamas;
    }

    public byte getCntBannos() {
        return cntBannos;
    }

    public void setCntBannos(byte cntBannos) {
        this.cntBannos = cntBannos;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public boolean getAireAcondicionado() {
        return aireAcondicionado;
    }

    public void setAireAcondicionado(boolean aireAcondicionado) {
        this.aireAcondicionado = aireAcondicionado;
    }

    public boolean getParrillero() {
        return parrillero;
    }

    public void setParrillero(boolean parrillero) {
        this.parrillero = parrillero;
    }

    public short getCostoHour() {
        return costoHour;
    }

    public void setCostoHour(short costoHour) {
        this.costoHour = costoHour;
    }
         
    
    
    
    public ingCabanna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCntCamas = new javax.swing.JLabel();
        lblCntHabitaciones = new javax.swing.JLabel();
        lblCntBannos = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        checkAireAcondicionado = new javax.swing.JCheckBox();
        checkParrillero = new javax.swing.JCheckBox();
        lblCosto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        fieldCostoHour = new javax.swing.JTextField();
        fieldCntHabitaciones = new javax.swing.JTextField();
        fieldCntBannos = new javax.swing.JTextField();
        fieldCntCamas = new javax.swing.JTextField();

        setBackground(new java.awt.Color(178, 34, 34));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Cabaña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCntCamas.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCntCamas.setForeground(new java.awt.Color(255, 255, 255));
        lblCntCamas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCntCamas.setText("Cantidad de Camas");

        lblCntHabitaciones.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCntHabitaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblCntHabitaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCntHabitaciones.setText("Cantidad de Habitaciones");

        lblCntBannos.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCntBannos.setForeground(new java.awt.Color(255, 255, 255));
        lblCntBannos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCntBannos.setText("Cantidad de Baños");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scrollDescripcion.setViewportView(txtDescripcion);

        checkAireAcondicionado.setBackground(new java.awt.Color(178, 34, 34));
        checkAireAcondicionado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        checkAireAcondicionado.setForeground(new java.awt.Color(255, 255, 255));
        checkAireAcondicionado.setText("Aire Acondicionado");

        checkParrillero.setBackground(new java.awt.Color(178, 34, 34));
        checkParrillero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        checkParrillero.setForeground(new java.awt.Color(255, 255, 255));
        checkParrillero.setText("Parrillero");

        lblCosto.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(255, 255, 255));
        lblCosto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCosto.setText("Costo por hora");

        btnGuardar.setText("Ingresar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCntCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldCntCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCntHabitaciones)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAireAcondicionado)
                            .addComponent(checkParrillero, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(scrollDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCntBannos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldCostoHour, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldCntHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldCntBannos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCntHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCntHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCntCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCntCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkAireAcondicionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkParrillero)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCntBannos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCntBannos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCostoHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        getInput();
        Cabanna nuevoRegistro=new Cabanna(cntHabitaciones, cntCamas, cntBannos, (byte)0, descripcion, aireAcondicionado, parrillero, costoHour);
        SQLCabanna test=new SQLCabanna();
        test.insertar(nuevoRegistro);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void getInput(){
        this.cntHabitaciones = Byte.parseByte(fieldCntHabitaciones.getText());
        this.cntCamas= Byte.parseByte(fieldCntCamas.getText());
        this.cntBannos = Byte.parseByte(fieldCntBannos.getText());
        this.descripcion = txtDescripcion.getText();
        this.aireAcondicionado = checkAireAcondicionado.isSelected();
        this.parrillero = checkParrillero.isSelected();
        this.costoHour = Short.parseShort(fieldCostoHour.getText());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JCheckBox checkAireAcondicionado;
    public javax.swing.JCheckBox checkParrillero;
    private javax.swing.JTextField fieldCntBannos;
    private javax.swing.JTextField fieldCntCamas;
    private javax.swing.JTextField fieldCntHabitaciones;
    private javax.swing.JTextField fieldCostoHour;
    private javax.swing.JLabel lblCntBannos;
    private javax.swing.JLabel lblCntCamas;
    private javax.swing.JLabel lblCntHabitaciones;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JScrollPane scrollDescripcion;
    public javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
