/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import javax.swing.JOptionPane;

/**
 *
 * @author Matías Garibotti
 */
public class Login_Duenno extends javax.swing.JFrame {

    /**
     * Creates new form Login_Duenno
     */
    public Login_Duenno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ui_Exit = new javax.swing.JLabel();
        ui_topBar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        pswContrasenna = new javax.swing.JPasswordField();
        lblContrasenna = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        ui_loginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ui_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_buttonEXIT.png"))); // NOI18N
        ui_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ui_ExitMousePressed(evt);
            }
        });
        getContentPane().add(ui_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 20, 20));

        ui_topBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_loginTopbar.png"))); // NOI18N
        getContentPane().add(ui_topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Dueño de cabaña");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        pswContrasenna.setText("jPasswordField1");
        getContentPane().add(pswContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, -1));

        lblContrasenna.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContrasenna.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenna.setText("Contraseña");
        getContentPane().add(lblContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnLogin.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 70, 25));

        ui_loginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_loginBackground.png"))); // NOI18N
        getContentPane().add(ui_loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ui_ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ui_ExitMousePressed
        this.dispose();
    }//GEN-LAST:event_ui_ExitMousePressed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        if(pswContrasenna.getText().equals("12345678")){
            Index.user.setNombre("Duenno");
            JOptionPane.showMessageDialog(null, "Usted se ha logueado como dueño");
        }else{
            Index.user.setNombre("root");
            JOptionPane.showMessageDialog(null, "Usted se ha logueado como encargado");
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Duenno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel lblContrasenna;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField pswContrasenna;
    private javax.swing.JLabel ui_Exit;
    private javax.swing.JLabel ui_loginBackground;
    private javax.swing.JLabel ui_topBar;
    // End of variables declaration//GEN-END:variables
}
