/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

/**
 *
 * @author Matías Garibotti
 */
public class Login_Duenno extends javax.swing.JFrame {

    /**
     * Creates new form Login_Duenno
     */
    public Login_Duenno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pswContraseña = new javax.swing.JPasswordField();
        lblContrasenna = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        ui_loginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Dueño de cabaña");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        pswContraseña.setText("jPasswordField1");
        getContentPane().add(pswContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, -1));

        lblContrasenna.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContrasenna.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenna.setText("Contraseña");
        getContentPane().add(lblContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnLogin.png"))); // NOI18N
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 70, 25));

        ui_loginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_loginBackground.png"))); // NOI18N
        getContentPane().add(ui_loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Duenno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Duenno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel lblContrasenna;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JLabel ui_loginBackground;
    // End of variables declaration//GEN-END:variables
}
