package grafica;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import logica.SQL.SQLCabanna;

public class Tools_Buscar extends javax.swing.JPanel {

    String view;

    /**
     * Panel con las herramientas que son necesarias en los menues con tablas.
     *
     */
    public Tools_Buscar() {
        this.view = "CABANNAS";

    }

    public Tools_Buscar(String view) {
        this.view = view;
    }

    public void build(DefaultComboBoxModel aModel) {
        initComponents();
        centerElements();
        this.setSize(454, 145);
        cmbFilter.setModel(aModel);
        
    }
    
    public DefaultComboBoxModel camposComboB(String view, DefaultComboBoxModel Def) {
        //Va a setear el modelo por defecto de los combo boxes
        Def = new DefaultComboBoxModel();
        switch (view) {
            case "TURISTAS":
                Def.addElement("CI");
                Def.addElement("Nombre");
                Def.addElement("Apellido");
                Def.addElement("Fecha Nacimiento");
                Def.addElement("Teléfono");
                Def.addElement("Calle");
                Def.addElement("Número");
                Def.addElement("Localidad");
                break;
            case "CABANNAS":
                Def.addElement("ID");
                Def.addElement("Nº Habitaciones");
                Def.addElement("Nº Camas");
                Def.addElement("Nº Baños");
                Def.addElement("Nº Huéspedes");
                Def.addElement("Descripción");
                Def.addElement("Aire Acon.");
                Def.addElement("Parrillero");
                Def.addElement("Costo Hr.");
                break;
            default:
                Def.addElement("Código");
                Def.addElement("Fecha Inicio");
                Def.addElement("Fecha Fin");
                Def.addElement("Confirmada");
                Def.addElement("Cancelada");
                Def.addElement("CI");
                Def.addElement("ID");
        }
        return Def;
    }
    
    public void horizontalView(){
        this.setSize(940, panelBuscar.getHeight());
        panelBuscar.setLocation(0, 0);
        this.repaint();
    }
    
    public void centerElements(){
        int height = lblBuscar.getHeight();
        fieldPattern.setSize(fieldPattern.getWidth(), height);
        cmbFilter.setSize(cmbFilter.getWidth(), height);
        
        lblBuscar.setLocation(20, panelBuscar.getHeight()/2-lblBuscar.getHeight()/2);
        fieldPattern.setLocation(lblBuscar.getLocation().x + lblBuscar.getWidth() + 10, panelBuscar.getHeight()/2-fieldPattern.getHeight()/2);
        cmbFilter.setLocation(fieldPattern.getLocation().x + fieldPattern.getWidth() + 10 , panelBuscar.getHeight()/2-cmbFilter.getHeight()/2);
        btnBuscar.setLocation(cmbFilter.getLocation().x + cmbFilter.getWidth() + 10 , panelBuscar.getHeight()/2-btnBuscar.getHeight()/2);
        panelBuscar.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        fieldPattern = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        panelBuscar.setBackground(new java.awt.Color(236, 235, 255));
        panelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        panelBuscar.setPreferredSize(new java.awt.Dimension(100, 83));
        panelBuscar.setLayout(null);

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(43, 41, 41));
        lblBuscar.setText("Buscar");
        lblBuscar.setMaximumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setMinimumSize(new java.awt.Dimension(46, 21));
        lblBuscar.setPreferredSize(new java.awt.Dimension(46, 21));
        panelBuscar.add(lblBuscar);
        lblBuscar.setBounds(10, 30, 50, 20);

        fieldPattern.setPreferredSize(new java.awt.Dimension(144, 21));
        panelBuscar.add(fieldPattern);
        fieldPattern.setBounds(70, 30, 144, 21);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnSearch.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        panelBuscar.add(btnBuscar);
        btnBuscar.setBounds(360, 30, 30, 30);

        cmbFilter.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbFilter.setForeground(new java.awt.Color(43, 41, 41));
        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        cmbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterActionPerformed(evt);
            }
        });
        panelBuscar.add(cmbFilter);
        cmbFilter.setBounds(230, 30, 120, 21);

        add(panelBuscar);
        panelBuscar.setBounds(0, 0, 454, 83);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilterActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        String patron = fieldPattern.getText();
        String atributo;

        switch (cmbFilter.getSelectedItem().toString()) {
            case "ID":
                atributo = "id";
                break;
            case "Nº Habitaciones":
                atributo = "cantHabitaciones";
                break;
            case "Nº Camas":
                atributo = "cantCamas";
                break;
            case "Nº Baños":
                atributo = "cantBannos";
                break;
            case "Nº Huéspedes":
                atributo = "cantHuespedes";
                break;
            case "Descripción":
                atributo = "descripcion";
                break;
            case "Aire Acon.":
                atributo = "aireAcondicionado";
                break;
            case "Parrillero":
                atributo = "parrillero";
                break;
            case "Costo Hr.":
                atributo = "costHour";
                break;
            default:
                atributo = "";
                break;
        }

        SQLCabanna sqlCabanna = new SQLCabanna();
        DefaultTableModel busqueda = sqlCabanna.select(patron, atributo);
        Index.paintTabla(busqueda, view);
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JTextField fieldPattern;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel panelBuscar;
    // End of variables declaration//GEN-END:variables
}
