/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

/**
 *
 * @author Matías Garibotti
 */
public class Tools_visualizar extends javax.swing.JPanel {

    String view;

    public Tools_visualizar() {
        this.view = "CABANNAS";

    }

    public Tools_visualizar(String view) {
        this.view = view;
    }

    public void build() {
        initComponents();
        this.setSize(450, 80);
        centerElements();
    }

    public void centerElements() {
        int startingWidth = this.getWidth() - btnVisualizar.getWidth() - cmbVisualizar.getWidth() - lblVisualizar.getWidth() * 2 - 10;
        int wHeigh = this.getHeight();
        int height = lblVisualizar.getHeight();
        
        cmbVisualizar.setSize(cmbVisualizar.getWidth(), height);
        btnVisualizar.setSize(btnVisualizar.getWidth(), height);

        lblVisualizar.setLocation(startingWidth, wHeigh / 2 - lblVisualizar.getHeight());
        cmbVisualizar.setLocation(lblVisualizar.getLocation().x + lblVisualizar.getWidth() + 15, wHeigh/2 - cmbVisualizar.getHeight());
        btnVisualizar.setLocation(cmbVisualizar.getLocation().x + cmbVisualizar.getWidth() + 15, wHeigh/2 - btnVisualizar.getHeight());
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbVisualizar = new javax.swing.JComboBox<>();
        lblVisualizar = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 235, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(null);

        cmbVisualizar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbVisualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Mes" }));
        add(cmbVisualizar);
        cmbVisualizar.setBounds(140, 20, 120, 22);

        lblVisualizar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblVisualizar.setText("Visualizar");
        add(lblVisualizar);
        lblVisualizar.setBounds(50, 20, 80, 22);

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnVisualizar.png"))); // NOI18N
        btnVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarMouseClicked(evt);
            }
        });
        add(btnVisualizar);
        btnVisualizar.setBounds(270, 10, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarMouseClicked
        String itemSelected = cmbVisualizar.getSelectedItem().toString().toUpperCase();
    }//GEN-LAST:event_btnVisualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnVisualizar;
    private javax.swing.JComboBox<String> cmbVisualizar;
    private javax.swing.JLabel lblVisualizar;
    // End of variables declaration//GEN-END:variables
}
