/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import javax.swing.JOptionPane;
import logica.SQL.SQLReserva;

/**
 *
 * @author Matías Garibotti
 */
public class Window_Checkout extends javax.swing.JFrame {

    String view;

    public Window_Checkout() {
        initComponents();
        this.view = "CHECKOUT";
    }
    
    public void build(){
        
        this.setSize(600, 300);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        btnCheckIn = new javax.swing.JLabel();
        lblCi = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblCodigoReserva = new javax.swing.JLabel();
        fieldCodigoReserva = new javax.swing.JTextField();
        fieldCiTitular = new javax.swing.JTextField();
        ui_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnVolver.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(520, 260, 70, 30);

        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnCheckOut.png"))); // NOI18N
        btnCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckInMouseClicked(evt);
            }
        });
        jPanel1.add(btnCheckIn);
        btnCheckIn.setBounds(260, 190, 160, 38);

        lblCi.setBackground(new java.awt.Color(255, 255, 255));
        lblCi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCi.setForeground(new java.awt.Color(255, 255, 255));
        lblCi.setText("C.I del titular");
        jPanel1.add(lblCi);
        lblCi.setBounds(10, 140, 210, 30);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Check Out");
        jPanel1.add(lblTitle);
        lblTitle.setBounds(190, 20, 180, 40);

        lblCodigoReserva.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigoReserva.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCodigoReserva.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoReserva.setText("Código de Reserva");
        jPanel1.add(lblCodigoReserva);
        lblCodigoReserva.setBounds(10, 90, 210, 30);

        fieldCodigoReserva.setBackground(new java.awt.Color(195, 191, 242));
        fieldCodigoReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(fieldCodigoReserva);
        fieldCodigoReserva.setBounds(230, 90, 290, 30);

        fieldCiTitular.setBackground(new java.awt.Color(195, 191, 242));
        jPanel1.add(fieldCiTitular);
        fieldCiTitular.setBounds(230, 140, 290, 30);

        ui_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_checkinBackground.png"))); // NOI18N
        jPanel1.add(ui_background);
        ui_background.setBounds(0, 0, 600, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckInMouseClicked
        int codigo, ci;
        SQLReserva sql = new SQLReserva();

        try {
            codigo = Integer.parseInt(fieldCodigoReserva.getText());
            ci = Integer.parseInt(fieldCiTitular.getText());
            if (sql.confirmar(codigo, ci)) {
                JOptionPane.showMessageDialog(null, "Adiós, esperamos verte pronto.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo realizar el checkin", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Algo ha salido mal", "Mensaje", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnCheckInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCheckIn;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JTextField fieldCiTitular;
    private javax.swing.JTextField fieldCodigoReserva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCi;
    private javax.swing.JLabel lblCodigoReserva;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel ui_background;
    // End of variables declaration//GEN-END:variables
}
