/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import static grafica.Index.color_textHint;
import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.SQL.SQLReserva;
import logica.SQL.SQLTurista;
import logica.Turista;

/**
 *
 * @author Matías Garibotti
 */
public class Window_addHost extends javax.swing.JFrame {

    String view;
    Turista turista;

    public Window_addHost() {
        initComponents();
        this.view = "ADDHOST";
    }

    public void build() {

        this.setSize(900, 500);
        this.setLocationRelativeTo(null);

    }

    public void textHint(String txt, JTextField obj) { //Procedimiento para textHints
        if (obj.getText().equals(txt)) {
            obj.setText("");
            obj.setForeground(Color.BLACK);
        } else if (obj.getText().equals("")) {
            obj.setText(txt);
            obj.setForeground(color_textHint);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panelAdd = new javax.swing.JPanel();
        lblCI = new javax.swing.JLabel();
        fieldCI = new javax.swing.JFormattedTextField();
        lblNombre = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        fieldApellido = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        fieldFechaNac = new javax.swing.JFormattedTextField();
        lblTel = new javax.swing.JLabel();
        fieldTelefono = new javax.swing.JFormattedTextField();
        lblDireccion = new javax.swing.JLabel();
        fieldCalle = new javax.swing.JTextField();
        fieldNumero = new javax.swing.JTextField();
        fieldLocalidad = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JLabel();
        fieldCodigo = new javax.swing.JFormattedTextField();
        lblCI1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(54, 46, 155));
        panel.setLayout(null);

        panelAdd.setBackground(new java.awt.Color(236, 235, 255));
        panelAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        panelAdd.setLayout(null);

        lblCI.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCI.setForeground(new java.awt.Color(43, 41, 41));
        lblCI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCI.setText("Código*");
        panelAdd.add(lblCI);
        lblCI.setBounds(200, 30, 70, 22);

        try {
            fieldCI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldCI.setCaretColor(new java.awt.Color(43, 41, 41));
        panelAdd.add(fieldCI);
        fieldCI.setBounds(90, 30, 100, 22);

        lblNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(43, 41, 41));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre*");
        panelAdd.add(lblNombre);
        lblNombre.setBounds(10, 70, 62, 22);

        fieldNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNombre.setCaretColor(new java.awt.Color(43, 41, 41));
        fieldNombre.setPreferredSize(new java.awt.Dimension(60, 25));
        panelAdd.add(fieldNombre);
        fieldNombre.setBounds(90, 70, 100, 25);

        lblApellido.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(43, 41, 41));
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblApellido.setText("Apellido*");
        panelAdd.add(lblApellido);
        lblApellido.setBounds(10, 110, 61, 22);

        fieldApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldApellido.setCaretColor(new java.awt.Color(43, 41, 41));
        fieldApellido.setPreferredSize(new java.awt.Dimension(60, 25));
        panelAdd.add(fieldApellido);
        fieldApellido.setBounds(90, 110, 100, 25);

        lblFechaNac.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblFechaNac.setForeground(new java.awt.Color(43, 41, 41));
        lblFechaNac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFechaNac.setText("Nacimiento*");
        panelAdd.add(lblFechaNac);
        lblFechaNac.setBounds(10, 150, 83, 22);

        try {
            fieldFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldFechaNac.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaNac.setCaretColor(new java.awt.Color(43, 41, 41));
        panelAdd.add(fieldFechaNac);
        fieldFechaNac.setBounds(100, 150, 80, 22);

        lblTel.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblTel.setForeground(new java.awt.Color(43, 41, 41));
        lblTel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTel.setText("Teléfono*");
        panelAdd.add(lblTel);
        lblTel.setBounds(10, 190, 65, 22);

        try {
            fieldTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fieldTelefono.setCaretColor(new java.awt.Color(43, 41, 41));
        panelAdd.add(fieldTelefono);
        fieldTelefono.setBounds(90, 190, 100, 22);

        lblDireccion.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(43, 41, 41));
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion.setText("Dirección*");
        panelAdd.add(lblDireccion);
        lblDireccion.setBounds(10, 230, 69, 22);

        fieldCalle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldCalle.setText("Calle");
        fieldCalle.setToolTipText("");
        fieldCalle.setCaretColor(new java.awt.Color(43, 41, 41));
        fieldCalle.setPreferredSize(new java.awt.Dimension(60, 25));
        fieldCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCalleFocusLost(evt);
            }
        });
        panelAdd.add(fieldCalle);
        fieldCalle.setBounds(90, 230, 60, 22);

        fieldNumero.setText("Numero");
        fieldNumero.setCaretColor(new java.awt.Color(43, 41, 41));
        fieldNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNumeroFocusLost(evt);
            }
        });
        panelAdd.add(fieldNumero);
        fieldNumero.setBounds(160, 230, 60, 22);

        fieldLocalidad.setText("Localidad");
        fieldLocalidad.setCaretColor(new java.awt.Color(43, 41, 41));
        fieldLocalidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldLocalidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldLocalidadFocusLost(evt);
            }
        });
        panelAdd.add(fieldLocalidad);
        fieldLocalidad.setBounds(230, 230, 70, 22);

        btnIngresar.setText("Añadir Huésped");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        panelAdd.add(btnIngresar);
        btnIngresar.setBounds(200, 290, 110, 23);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ui/ui_btnVolver.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        panelAdd.add(btnVolver);
        btnVolver.setBounds(100, 290, 70, 30);
        panelAdd.add(fieldCodigo);
        fieldCodigo.setBounds(280, 30, 80, 20);

        lblCI1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCI1.setForeground(new java.awt.Color(43, 41, 41));
        lblCI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCI1.setText("CI*");
        panelAdd.add(lblCI1);
        lblCI1.setBounds(20, 30, 21, 22);

        panel.add(panelAdd);
        panelAdd.setBounds(20, 70, 360, 340);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Check In");
        panel.add(lblTitle);
        lblTitle.setBounds(360, 0, 180, 40);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tabla);

        panel.add(scroll);
        scroll.setBounds(430, 70, 440, 340);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        Window_Checkin wCheckIn = new Window_Checkin();
        wCheckIn.build();
        wCheckIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void fieldCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCalleFocusGained

        Index idx = new Index();
        idx.textHint("Calle", fieldCalle);
    }//GEN-LAST:event_fieldCalleFocusGained

    private void fieldCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCalleFocusLost
        Index idx = new Index();
        idx.textHint("Calle", fieldCalle);
    }//GEN-LAST:event_fieldCalleFocusLost

    private void fieldNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroFocusGained
        Index idx = new Index();
        idx.textHint("Numero", fieldNumero);
    }//GEN-LAST:event_fieldNumeroFocusGained

    private void fieldNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNumeroFocusLost
        Index idx = new Index();
        idx.textHint("Numero", fieldNumero);
    }//GEN-LAST:event_fieldNumeroFocusLost

    private void fieldLocalidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldLocalidadFocusGained
        Index idx = new Index();
        idx.textHint("Localidad", fieldLocalidad);
    }//GEN-LAST:event_fieldLocalidadFocusGained

    private void fieldLocalidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldLocalidadFocusLost
        Index idx = new Index();
        idx.textHint("Localidad", fieldLocalidad);
    }//GEN-LAST:event_fieldLocalidadFocusLost

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked

        if (Panel_Reservar.verificarCi(Integer.parseInt(fieldCI.getText()))) {
            SQLTurista sql = new SQLTurista();
            
            turista = new Turista(
                    Integer.parseInt(fieldCI.getText()),
                    fieldNombre.getText(),
                    fieldApellido.getText(),
                    toDate(fieldFechaNac),
                    Integer.parseInt(fieldTelefono.getText()),
                    fieldCalle.getText(),
                    Short.parseShort(fieldNumero.getText()),
                    fieldLocalidad.getText()
            );
            
            if (sql.insertar(turista)){
                JOptionPane.showMessageDialog(null, "Turista ingresado con éxito a la permanencia.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(null, "Error en el ingreso del turista.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            
            //Realizar SQL para poder agregar a la tabla los turístas
            SQLReserva sqlReserva=new SQLReserva();
            if (sqlReserva.addHost(Integer.parseInt(fieldCodigo.getText()),turista.getCi())){
                JOptionPane.showMessageDialog(null, "Turista ingresado con éxito al la reserva.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }else
                JOptionPane.showMessageDialog(null, "Error en el ingreso del turista-reserva.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnIngresarMouseClicked

    public Date toDate(JTextField field) {  //A partir de un JTextField obtengo la fecha que contiene
        Panel_Reservar reservar = new Panel_Reservar();
        int day = reservar.getDay(field.getText());
        int month = reservar.getMonth(field.getText());
        int year = reservar.getYear(field.getText());

        Date result = new Date(year - 1900, month - 1, day);
        return result;
    }

    public int getDay(String date) {
        int day = Integer.parseInt(date.substring(0, 2));
        return day;
    }

    public int getMonth(String date) {
        int month = Integer.parseInt(date.substring(3, 5));
        return month;
    }

    public int getYear(String date) {
        int year = (Integer.parseInt(date.substring(6, 10)));
        return year;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_addHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_addHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_addHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_addHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_addHost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel btnVolver;
    public javax.swing.JTextField fieldApellido;
    public javax.swing.JFormattedTextField fieldCI;
    public javax.swing.JTextField fieldCalle;
    public javax.swing.JFormattedTextField fieldCodigo;
    public javax.swing.JFormattedTextField fieldFechaNac;
    public javax.swing.JTextField fieldLocalidad;
    public javax.swing.JTextField fieldNombre;
    public javax.swing.JTextField fieldNumero;
    public javax.swing.JFormattedTextField fieldTelefono;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCI;
    private javax.swing.JLabel lblCI1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
